kyc/urls.py
# kyc/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('kyc/', views.kyc_view, name='kyc_view'),
    path('kyc-success/', views.kyc_success, name='kyc_success'),
    path('form/', views.kyc_view, name='kyc_form'),
    path('success/', views.kyc_success, name='kyc_success'),
    path('status/', views.kyc_status, name='kyc_status'),
    path('admin/', views.kyc_admin_view, name='kyc_admin_view'),
    path('admin/action/<int:kyc_id>/', views.kyc_action, name='kyc_action'),
    
]

paytev/urls.py
# urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.models import AppInfo

# Function to get the admin URL dynamically
def get_admin_url():
    try:
        app_info = AppInfo.objects.first()
        return app_info.admin_url if app_info else 'admin'
    except:
        return 'admin'

admin_url = get_admin_url()

urlpatterns = [
    path(f'{admin_url}/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('airtime_recharge/', include('airtime_recharge.urls')),
    path('paystack/', include('paystack.urls', namespace='paystack')),
    path('bills/', include('bills.urls')),
    path('transactions/', include('transactions.urls')),
    path('strowallet/', include('strowallet.urls')),
    path('monnify/', include('monnify.urls')),
]

# Serving static and media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from transactions.views import *
from . import views
from transactions.views import transactions, transactions_details, transaction_list, transactions_failed


app_name = 'transactions'
urlpatterns = [
    path('history/', views.transactions, name='transactions'),
    path('transactions/', transactions, name='list_tranasactions'),
    path('history/', views.transactions, name='transactions'),
    path('history/', transactions, name='list_transactions'),
    path('i/<str:reference>/', transactions_details,
         name='transactions_details_page'),
    path('bill/<str:reference>/', transactions_failed,
         name='transactions_details_failed'),
    path('api/transaction-list/', transaction_list, name='transaction_list'),
]

transactions/models.py
from django.db import models

# Create your models here.
import time
import random
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.core.exceptions import ValidationError
from django.utils import timezone
from account.models import CustomUser
from django.db import models

# Create your models here.
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL

CHOICES = (
    ("QUEUE", "QUEUE"),
    ("FAILED", "FAILED"),
    ("REFUNDED", "REFUNDED"),
   	("SUCCESS", "SUCCESS"),
)


class Transactions(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_transactions")
    status = models.CharField(max_length=50, blank=True, null=True)
    identifier = models.CharField(default="", max_length=50)
    bill_type = models.CharField(max_length=500, blank=True, null=True)
    bill_code = models.CharField(max_length=500, blank=True, null=True)
    bill_number = models.CharField(max_length=300, blank=True, null=True)
    bill_serial = models.CharField(max_length=500, blank=True, null=True)
    bill_provider = models.CharField(max_length=500, blank=True, null=True)
    actual_amount = models.FloatField(default=0.0)
    paid_amount = models.FloatField(default=0.0)
    discount = models.FloatField(default=0.0)
    old_balance = models.FloatField(default=0.0)
    new_balance = models.FloatField(default=0.0)
    comment = models.CharField(max_length=500, blank=True, null=True)
    reference = models.CharField(max_length=300, blank=True, null=True)
    customernumber = models.CharField(
        default='', max_length=30, blank=True, null=True)
    customername = models.CharField(
        default='', max_length=30, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    customer_dt_number = models.CharField(
        max_length=100, default='', blank=True, null=True)

    

    api_id = models.IntegerField(blank=True, null=True)

    # for account funding
    smsangosbulkcredit = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="wallet_funding", null=True, blank=True)
    amtcredited = models.FloatField(blank=True, null=True)
    # end for account funding

    api_response = models.TextField(max_length=20000, blank=True, null=True)
    callback_url = models.TextField(max_length=20000, blank=True, null=True)
    callback_done = models.BooleanField(default=False)
    mode = models.CharField(max_length=200, default="DIRECT")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


@receiver(pre_save, sender=Transactions)
def transaction_pre_save_receiver(sender, **kwargs):
    instance = kwargs['instance']
    print(instance, kwargs)
    if instance and not kwargs['update_fields']:
        try:
            t = Transactions.objects.all()
            if t.count() > 0:
                getLastOne = t.last()
                print(int(timezone.now().timestamp()) -
                      int(getLastOne.created_at.timestamp()), "sept")
                if (int(timezone.now().timestamp()) - int(getLastOne.created_at.timestamp()) <= 5) \
                        and (getLastOne.user == instance.user) and (instance.bill_number == getLastOne.bill_number) and\
                        instance.status == "SUCCESS" and instance.mode != "API":
                    raise ValidationError("Wait Please")
                else:
                    pass
            else:
                pass

        except Exception as e:
            raise e
    else:
        pass

transactions/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q
from transactions.models import Transactions

@login_required(login_url=settings.LOGIN_URL)
def transactions(request):
    # Determine the page number and search term from the request
    search_term = request.GET.get('search', '')
    page_number = request.GET.get('page', 1)

    # Fetch transactions based on user permissions
    if request.user.is_superuser:
        transactions = Transactions.objects.all().order_by("-created_at")
    else:
        transactions = Transactions.objects.filter(user=request.user).order_by("-created_at")

    # Apply search filter if a search term is provided
    if search_term:
        transactions = transactions.filter(
            Q(reference__icontains=search_term) |
            Q(bill_number__icontains=search_term) |
            Q(status__icontains=search_term) |
            Q(bill_type__icontains=search_term)
        )

    # Paginate transactions
    paginator = Paginator(transactions, 20)  # Show 20 transactions per page
    try:
        page_obj = paginator.page(page_number)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    # Pass the transactions and search term to the template
    context = {
        'transactions': page_obj,
    }
    return render(request, "transactions/history.html", context)

@login_required(login_url=settings.LOGIN_URL)
def transactions_details(request, reference):
    # Fetch and return transaction details based on reference
    transaction = get_object_or_404(Transactions, reference=reference)
    return render(request, "i/transaction_details.html", {"transaction": transaction})

@login_required(login_url=settings.LOGIN_URL)
def transaction_list(request):
    # Determine the page number from the request
    search_term = request.GET.get('search', '')
    page_number = request.GET.get('page', 1)

    # Fetch transactions based on user permissions
    if request.user.is_superuser:
        transactions = Transactions.objects.all().order_by("-created_at")
    else:
        transactions = Transactions.objects.filter(user=request.user).order_by("-created_at")

    if search_term:
        transactions = transactions.filter(
            Q(reference__icontains=search_term) |
            Q(bill_number__icontains=search_term) |
            Q(status__icontains=search_term) |
            Q(bill_type__icontains=search_term)
        )

    # Paginate transactions
    paginator = Paginator(transactions, 50)  # Show 50 transactions per page
    try:
        page_obj = paginator.page(page_number)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    # Prepare response data
    data = {
        'transactions': list(page_obj.object_list.values(
            'id', 'reference', 'bill_number', 'created_at', 'status', 'paid_amount', 'bill_type'
        )),
        'has_next': page_obj.has_next(),
        'total_count': transactions.count(),
    }
    return JsonResponse(data)

@login_required(login_url=settings.LOGIN_URL)
def transactions_details(request, reference):
    # Fetch and return transaction details based on reference
    obj = Transactions.objects.get(reference=reference)
    response = None
    if obj.api_response:
        response = obj.api_response
    return render(request, "transactions/details.html", {"data": obj, "response": response})

@login_required(login_url=settings.LOGIN_URL)
def transactions_failed(request, reference):
    # Fetch and return transaction details for failed transactions
    obj = Transactions.objects.get(reference=reference)
    response = None
    if obj.api_response:
        response = obj.api_response
    return render(request, "i/failed.html", {"data": obj, "response": response})

transactions/templates/transactions/details.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Paytev">
    <meta name="author" content="Paytev">
    <title>Receipt</title>
    {% if app_info.app_logo %}
    <link rel="icon" href="{{ app_info.app_logo.url }}" type="image/png">
    {% else %}
    <link rel="icon" href="{% static 'path/to/default/favicon.png' %}" type="image/png">
    {% endif %}

    <!-- CSS FILES -->      
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;700&display=swap" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/apexcharts.css' %}" rel="stylesheet">
    <link href="{% static 'css/tooplate-mini-finance.css' %}" rel="stylesheet"> 
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script> 
    <style>
        .btn-active {
            background-color: #062863; /* Active button color */
            color: #fff;
            cursor: pointer;
        }

        .btn-inactive {
            background-color: #b0bec5; /* Inactive button color */
            color: #6c757d;
            cursor: not-allowed;
        }

        .right-sidebar {
            background-color: #f8f9fa;
            padding: 15px;
            border-left: 1px solid #ddd;
            border-radius: 10px;
            width: 100%;
            max-width: 400px; /* Adjust as needed */
            margin: 0 auto;
        }

        .right-sidebar h5 {
            margin-top: 0;
            margin-bottom: 15px;
            font-size: 18px;
            font-weight: bold;
        }

        .right-sidebar p {
            margin-bottom: 10px;
        }

        /* Modal Design */
        .modal-content {
            border-radius: 10px;
            border: none;
            box-shadow: 0 4px 8px rgba(0,0,0,0.2);
            text-align: center;
        }

        .modal-dialog {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .modal-header {
            border-bottom: none;
            background-color: #062863;
            color: #fff;
            border-radius: 10px 10px 0 0;
            text-align: center;
        }

        .modal-title {
            font-size: 1.25rem;
            color: white;
            margin: -9px;
        }

        .modal-body {
            padding: 2rem;
            text-align: center;
            margin: -15px 0px -32px 0px;
            
        }

        .modal-footer {
            border-top: none;
            
        }

        .btn-confirm {
            background-color: #062863;
            color: #fff;
            border: none;
        }

        .btn-cancel {
            background-color: #f8f9fa;
            color: #333;
            border: none;
        }

        .btn-confirm:hover {
            background-color: #041a40;
            color: #FAF9F6;
        }

        .btn-cancel:hover {
            background-color: #e2e6ea;
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% include "account/navbar.html" %}
    {% include "account/sidebar.html" %}
    <main class="main-wrapper row ms-sm-auto py-4 col-lg-9 px-md-4 border-start">
        <!-- Main Content Area -->
        <!--<div class="col-md-8 col-lg-8">-->
            <div class="title-group mb-3"> 
               
                <h1 class="h2 mb-0"><i class="fa fa-wifi" style="font-size:30px;color:#062863;text-shadow:1px 1px 1px #5ad3db;"></i> Receipt</h1>

<br>
<center> {% if messages %}
    <div class="alert alert-danger">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %} </center>


<center>
                <p>{% if "successfully" in data.api_response or "GIFTED" in data.api_response or "dial" in data.api_response or "gifted" in data.api_response or  "delivered" in data.api_response %}
                    <div style="background-color: #4CAF50; color: white; padding: 10px; border-radius: 10px; text-align: center; font-weight: bold; font-size: 20px;">
                        {{data.bill_type}} RECHARGE DELIVERED SUCCESSFULLY
                    </div>
                                    {% elif "invalid mobile number" in data.api_response %}
                                        Failed: Invalid number
                                        <hr>
                                        {% elif "valid MTN phone number" in data.api_response %}
                                        Failed: Please enter a valid MTN phone number and try again
                                        <hr>
                					{% else %}
                					    {{data.status}}
                					{% endif %}</p>
                                    <hr>
                         <p>Receiver: {{data.bill_number}}</p>
                         <hr>
                         <p>Order ID: {{data.reference}}</p>
                         <hr>
                         <b>Transaction Details</b>
                         <hr>
                             <p>Plan Code: {{data.bill_code}}</p>
                             <hr>
                             <p>Date: <span>{{data.created_at}}</span> </p>
                              <hr>
                             <p>Product: <span class="text-end">{{data.bill_type}}</span> </p>
                             <hr>
                             <a href="{% url 'dashboard' %}" style="background-color: #062863; color: #ffffff; padding: 10px 20px; text-decoration: none; border-radius: 7px; font-size: 15px;">Back to Dashboard</a>     
    </center>





    <script type="text/javascript" src="{% static 'javascript/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/count-down.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/main.js' %}"></script>

</body>



</html>

transactions/templates/transactions/history.html
<!doctype html>
<html lang="en">
    {% load static %}
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    {% if app_info.app_logo %}
    <link rel="icon" href="{{ app_info.app_logo.url }}" type="image/png">
{% else %}
    <link rel="icon" href="{% static 'path/to/default/favicon.png' %}" type="image/png">
{% endif %}


        <meta name="description" content="Paytev">
        <meta name="author" content="Paytev">

        <title>Transaction History</title>

        <!-- CSS FILES -->      
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;700&display=swap" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">
        <link href="{% static 'css/apexcharts.css' %}" rel="stylesheet">
        <link href="{% static 'css/tooplate-mini-finance.css' %}" rel="stylesheet"> 
        <style>
            .modal-dialog {
                max-width: 75%; /* Adjust width for smaller screens */
                margin: auto; /* Center the modal horizontally */
            }
            .modal-content {
                font-size: 7px; 
                padding: 0.5rem; 
            }
            .modal-body p {
                display: flex;
                justify-content: space-between;
                margin-bottom: 1px;
                font-size: 12px; 
            }
            .modal-body img {
                width: 45px; 
                height: auto;
            }
            .copy-btn {
                cursor: pointer;
                border: none;
                background: none;
                color: #007bff;
                font-size: 0.8rem; /* Smaller icon size */
                margin-left: 0px;
            }
            .copy-btn:hover {
                text-decoration: underline;
            }
            .copy-btn.copied {
                color: #28a745; /* Green color for 'copied' state */
            }
        </style>
        
    </head>

    {% include "account/navbar.html" %}
    {% include "account/sidebar.html" %}

    <main class="main-wrapper col-md-9 ms-sm-auto py-4 col-lg-9 px-md-4 border-start">
        <div class="title-group mb-3">
            <h5 class="mb-4">Transaction Histories</h5>

            <!-- Search Form -->
            <form method="get" action="{% url 'transactions:transactions' %}" class="d-flex mb-4">
                <input class="form-control me-2" type="search" name="search" placeholder="Search by Order ID, Status, etc." aria-label="Search" value="{{ request.GET.search }}">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>

        <div class="row my-4">
            <div class="col-lg-12 col-12">
                <div class="custom-block bg-white">
                    <div class="table-responsive">
                        <table class="account-table table">
                            <thead>
                                <tr>
                                    <th scope="col">S/N</th>
                                    <th scope="col">Order ID</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Old Balance</th>
                                    <th scope="col">New Balance</th>
                                    <th scope="col">Product</th>
                                    <th scope="col">Phone</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Identifier</th>
                                    <th scope="col">Code</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Receipt</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if transactions %}
                                    {% for transaction in transactions %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ transaction.reference }}</td>
                                        <td>{{ transaction.paid_amount }}</td>
                                        <td>{{ transaction.old_balance }}</td>
                                        <td>{{ transaction.new_balance }}</td>
                                        <td>{{ transaction.bill_type }}</td>
                                        <td>{{ transaction.bill_number }}</td>
                                        <td>{{ transaction.created_at }}</td>
                                        <td>{{ transaction.identifier }}</td>
                                        <td>{{ transaction.bill_code }}</td>
                                        <td>
                                            <span class="badge {% if transaction.status == 'Success' %}text-bg-success{% else %}text-bg-danger{% endif %}">
                                                {{ transaction.status }}
                                            </span>
                                        </td>
                                        <td>
                                            <!-- View Receipt Button -->
                                            <button type="button" class="btn btn-sm" style="background-color: #062863; color: white;" data-bs-toggle="modal" data-bs-target="#receiptModal{{ transaction.id }}">
                                                <i class="fa fa-eye"> View</i>
                                            </button>
                                            
                                            <!-- Receipt Modal -->
                                            <div class="modal fade" id="receiptModal{{ transaction.id }}" tabindex="-1" aria-labelledby="receiptModalLabel{{ transaction.id }}" aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered">
                                                    <div class="modal-content">
                                                        <div class="modal-body">
                                                            <div class="text-center mb-2">
                                                                <img src="https://client.paytev.com/media/Paytev_Icon.png" alt="Paytev Logo">
                                                            </div>
                                                            <p><strong>Order ID:</strong> <span id="order-id{{ transaction.id }}">{{ transaction.reference }}<button class="copy-btn" onclick="copyToClipboard('{{ transaction.reference }}', this)"><i class="bi bi-clipboard"></i> <span class="copy-status"></span></button></p><hr>
                                                            <p><strong>Amount Paid:</strong> <span>{{ transaction.paid_amount }}</span></p><hr>
                                                            <p><strong>Old Balance:</strong> <span>{{ transaction.old_balance }}</span></p><hr>
                                                            <p><strong>New Balance:</strong> <span>{{ transaction.new_balance }}</span></p><hr>
                                                            <p><strong>Product:</strong> <span>{{ transaction.bill_type }}</span></p><hr>
                                                            <p><strong>Phone:</strong> <span>{{ transaction.bill_number }}</span></p><hr>
                                                            <p><strong>Date:</strong> <span>{{ transaction.created_at }}</span></p><hr>
                                                            <p><strong>Identifier:</strong> <span>{{ transaction.identifier }}</span></p><hr>
                                                            <p><strong>Size:</strong> <span>{{ transaction.bill_code }}</span></p><hr>
                                                            <p><strong>Mode:</strong> <span>{{ transaction.mode }}</span></p><hr>
                                                            <p><strong>Status:</strong> <span>{{ transaction.status }}</span></p>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="12" class="text-center"><h4>Hello {{ user.username }}, you have no transaction history yet</h4></td>
                                    </tr>
                                {% endif %}
                            </tbody>
                            
                        </table>
                    </div>

                    <!-- Pagination -->
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center mb-0">
                            {% if transactions.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ transactions.previous_page_number }}&search={{ request.GET.search }}" aria-label="Previous">
                                    <span aria-hidden="true">Prev</span>
                                </a>
                            </li>
                            {% endif %}

                            {% for page_num in transactions.paginator.page_range %}
                            <li class="page-item {% if page_num == transactions.number %}active{% endif %}">
                                <a class="page-link" href="?page={{ page_num }}&search={{ request.GET.search }}">{{ page_num }}</a>
                            </li>
                            {% endfor %}

                            {% if transactions.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ transactions.next_page_number }}&search={{ request.GET.search }}" aria-label="Next">
                                    <span aria-hidden="true">Next</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-12">
                        <p class="copyright-text">Copyright © 2024
                        - <a href="https://www.paytev.com" target="_blank">Paytev</a></p>
                    </div>
                </div>
            </div>
        </footer>
    </main>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>

    <script>
        function copyToClipboard(text, button) {
            navigator.clipboard.writeText(text).then(function() {
                // Show "copied" status
                var statusSpan = button.nextElementSibling;
                button.classList.add('copied');
                statusSpan.textContent = 'Copied';
                // Reset after 2 seconds
                setTimeout(function() {
                    statusSpan.textContent = '';
                    button.classList.remove('copied');
                }, 2000);
            }).catch(function(err) {
                console.error('Failed to copy text: ', err);
            });
        }
    </script>
</html>